# This supplementary file may be used to create an environment using:
# conda env create -n tagmaps -f environment.yml
# conda activate tagmaps
# pip install --no-deps --editable .
name: tagmaps
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.7
  - pip
  - fiona==1.8.22 # pin until fiona-feedstock/issues/213 is solved
  - shapely
  - pandas>=0.24.2
  - pyproj>=2.0.0
  - numpy
  - matplotlib-base>=3.0.0
  - emoji>=2.0.0
  - hdbscan>=0.8.31
  - seaborn
  - scipy

