name: tagmaps
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.5
  - pip
  - fiona
  - shapely
  - pandas>=0.24.2
  - pyproj>=1.9.6
  - numpy
  - matplotlib
  - emoji>=0.5.1
  - cython
  - hdbscan>=0.8.20
  - gdal
  - attrs
  - seaborn
  - descartes
  - regex
  - scipy
  - six
  - joblib
