name: tagmaps
channels:
  - conda-forge
  - defaults
dependencies:
  - python >=3.7
  - pip
  - fiona
  - shapely
  - pandas >=0.24.2
  - pyproj >=2.0.0
  - numpy
  - matplotlib-base
  - emoji >=1.0.1
  - cython
  - hdbscan >=0.8.20
  - gdal
  - seaborn
  - descartes
  - regex
  - scipy
  - joblib
